package project2;

import java.awt.event.KeyEvent;

/**
  * This class implements the initial GUI which will allow the user to choose
  * to continue into calculating GCD or factorial in a different GUI/dialog.
  *
  * @author James Osborne
  * @version 1.0  
  * File: Project2UI.java
  * Created: 16 Sept 2016
  * ©Copyright James Osborne. All rights reserved.
  * Summary of Modifications:
  *     16 Sept 2016 – JAO – Created all the visuals of this GUI.
  *     20 Sept 2016 - JAO - Added the events for menu items and 
  *     closing with the ESC key.
  * 
  * Description: This class provides the design and functionality of the 
  * initial GUI which will allow the user to access the GCD and Factorial GUIs.
  */
public class Project2UI extends javax.swing.JFrame {

    /**
     * Creates new form Project2UI
     */
    public Project2UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitItem = new javax.swing.JMenuItem();
        computeMenu = new javax.swing.JMenu();
        gcdItem = new javax.swing.JMenuItem();
        factorialItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemAction(evt);
            }
        });
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);

        computeMenu.setText("Compute");

        gcdItem.setText("GCD");
        gcdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcdItemAction(evt);
            }
        });
        computeMenu.add(gcdItem);

        factorialItem.setText("Factorial");
        factorialItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialItemAction(evt);
            }
        });
        computeMenu.add(factorialItem);

        jMenuBar1.add(computeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Closes the entire program when exit menu item is selected.
    private void exitItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemAction
        System.exit(0);
    }//GEN-LAST:event_exitItemAction

    //Declares and initializes thee GCD GUI.
    private void gcdItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcdItemAction
        GCDDialog gcdDial = new GCDDialog(new javax.swing.JFrame(), true);
        
        //Makes the dialog visible to the user.
        gcdDial.setVisible(true);
        //Makes it so when dialog is shown, you cannot select from initial GUI.
        gcdDial.setModal(true);
    }//GEN-LAST:event_gcdItemAction

    //Declarss and initializes the Factorial GUI.
    private void factorialItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialItemAction
        FactorialDialog factorialDial = 
        new FactorialDialog(new javax.swing.JFrame(), true);
        
        //Makes the GUI visible to the user.
        factorialDial.setVisible(true);     
        //Makes it so when dialog is shown, you cannot select from initial GUI.
        factorialDial.setModal(true);
    }//GEN-LAST:event_factorialItemAction

    //If user presses the ESC key in this GUI, it will close the entire program,
    //not only the initial GUI.
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project2UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu computeMenu;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuItem factorialItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem gcdItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}